export const ERROR_CODES = {
  generic: {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  },

  user: {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  },

  auth: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
    WEAK_PASSWORD: 'WEAK_PASSWORD',
    UNAUTHORIZED: 'UNAUTHORIZED',
  },

  token: {
    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_ALREADY_USED: 'TOKEN_ALREADY_USED',
  },

  oauth: {
    OAUTH_ACCOUNT_NOT_FOUND: 'OAUTH_ACCOUNT_NOT_FOUND',
    OAUTH_ACCOUNT_ALREADY_LINKED: 'OAUTH_ACCOUNT_ALREADY_LINKED',
  },

  session: {
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    SESSION_INVALID: 'SESSION_INVALID',
  },
} as const;
